/* Portable creator backup. No account cookies, credentials or platform sessions. */
(() => {
  'use strict';
  const B=window.CreatorBackend,MAX=512*1048576;
  async function cached(databaseName,storeName){return new Promise((resolve,reject)=>{const q=indexedDB.open(databaseName,1);q.onupgradeneeded=()=>{if(!q.result.objectStoreNames.contains(storeName))q.result.createObjectStore(storeName,{keyPath:'id'});};q.onerror=()=>reject(q.error);q.onsuccess=()=>{const db=q.result,r=db.transaction(storeName).objectStore(storeName).getAll();r.onsuccess=()=>{db.close();resolve(r.result);};r.onerror=()=>{db.close();reject(r.error);};};});}
  async function create(record){const zip=new JSZip(),refs=new Map();let size=0;
    async function pack(value){if(value instanceof Blob){const id=await B.hash(value);if(!refs.has(id)){size+=value.size;if(size>MAX)throw new Error('备份超过 512 MB，请分别备份项目');const entry={id,path:'media/'+id,filename:value.name||'素材.zip',mime:value.type,size:value.size};refs.set(id,entry);zip.file(entry.path,value);}return {$creatorFile:id};}if(Array.isArray(value)){const out=[];for(const item of value)out.push(await pack(item));return out;}if(value&&typeof value==='object'){const out={};for(const [key,item]of Object.entries(value))if(key!=='url'&&!key.startsWith('_creator'))out[key]=await pack(item);return out;}return value;}
    const templates=B.connected?await B.list('templates'):await cached('qingjing-content-templates','templates'),favorites=B.connected?await B.list('favorites'):await cached('qingjing-content-media-library','favorites');
    const data=await pack({projects:[record],templates,favorites});zip.file('manifest.json',JSON.stringify({format:'qingjing-creator',version:1,createdAt:new Date().toISOString(),data,media:[...refs.values()]}));return zip.generateAsync({type:'blob',compression:'STORE'});
  }
  async function restore(file){if(file.size>MAX+10*1048576)throw new Error('备份文件过大');const zip=await JSZip.loadAsync(file),entry=zip.file('manifest.json');if(!entry||entry._data.uncompressedSize>10*1048576)throw new Error('备份清单无效');const manifest=JSON.parse(await entry.async('string'));if(manifest.format!=='qingjing-creator'||manifest.version!==1||!Array.isArray(manifest.media)||!Array.isArray(manifest.data?.projects)||manifest.data.projects.length!==1||manifest.media.length>5000)throw new Error('不支持的项目备份');let size=0;const files=new Map();for(const row of manifest.media){if(!/^file-[a-f0-9]{64}$/.test(row.id)||row.path!=='media/'+row.id||typeof row.filename!=='string'||/[\\/]/.test(row.filename))throw new Error('备份文件清单无效');const source=zip.file(row.path);if(!source||source._data.uncompressedSize!==row.size)throw new Error('备份素材不完整');size+=row.size;if(size>MAX)throw new Error('备份展开后超过 512 MB');const blob=await source.async('blob');if(await B.hash(blob)!==row.id)throw new Error('备份素材校验不通过');files.set(row.id,new File([blob],row.filename,{type:row.mime}));}
    const ids=new Map();for(const kind of ['projects','templates','favorites']){if(!Array.isArray(manifest.data[kind])||manifest.data[kind].length>5000)throw new Error('备份记录无效');for(const row of manifest.data[kind]){if(typeof row.id!=='string'||typeof row.name!=='string'||row.name.length>80)throw new Error('备份记录无效');ids.set(row.id,crypto.randomUUID());}}for(const asset of manifest.data.projects[0].media||[])ids.set(asset.id,crypto.randomUUID());
    function unpack(value){if(value?.$creatorFile){if(!files.has(value.$creatorFile))throw new Error('备份素材缺失');return files.get(value.$creatorFile);}if(typeof value==='string')return ids.get(value)||value;if(Array.isArray(value))return value.map(unpack);if(value&&typeof value==='object')return Object.fromEntries(Object.entries(value).map(([key,item])=>[ids.get(key)||key,unpack(item)]));return value;}
    const records=unpack(manifest.data),project=records.projects[0];if(!project.data||typeof project.data!=='object')throw new Error('项目快照无效');delete project.deletedAt;project.name=project.name.slice(0,60)+' · 恢复';project.data.name=project.name;project.data.productRecord=null;project.createdAt=project.updatedAt=new Date().toISOString();return records;
  }
  function open(H){H.modal('项目备份','<div class="content-template-form"><p>备份当前项目、素材、作品，以及本机模板和收藏。恢复时创建新副本，原项目保留。</p><button id="creator-backup-export">导出备份到本地</button><label>恢复备份<input id="creator-backup-import" type="file" accept=".zip"></label><p id="creator-backup-message" role="status"></p></div>',[{label:'返回编辑',run:H.close}]);document.getElementById('creator-backup-export').onclick=async event=>{event.target.disabled=true;const message=document.getElementById('creator-backup-message');try{message.textContent='正在打包项目…';const record=await H.record();H.download(window.ResourceExport.filename(record.name)+'-创作备份.zip',await create(record),'application/zip');message.textContent='备份已导出';}catch(error){message.textContent=error.message;}finally{event.target.disabled=false;}};document.getElementById('creator-backup-import').onchange=async event=>{const file=event.target.files[0];if(!file)return;event.target.disabled=true;const message=document.getElementById('creator-backup-message');try{await B.requireConnection();message.textContent='正在恢复项目…';await H.restore(await restore(file));H.toast('已恢复为新项目');}catch(error){if(message.isConnected)message.textContent=error.message;}finally{event.target.disabled=false;event.target.value='';}};}
  window.CreatorBackup={open};
})();
