/* Frozen input, durable encoding and completed-output reuse. */
(() => {
  'use strict';
  const B=window.CreatorBackend,esc=B.escape;
  let ui={},timer,viewRevision=0;
  async function snapshot(w,resolve){const input=JSON.parse(JSON.stringify(w));function clean(value){if(!value||typeof value!=='object')return;for(const key of Object.keys(value)){if(['cursor','view','selection','selectedClipId','selectedSurface','surfaceSelection','canvasHistory','templateId','templateVersion'].includes(key))delete value[key];else clean(value[key]);}}clean(input);delete input.id;const ids=new Set([...Object.values(w.slots||{}),...window.GalleryCore.assets(w),...window.ContentCore.all(w).map(c=>c.assetId)].filter(Boolean)),sources=[];for(const id of [...ids].sort()){const asset=resolve(id);if(!asset)throw new Error('生成素材已丢失，请重新导入');sources.push({id,hash:asset.file?await B.hash(asset.file):asset.demo?'demo-v1-'+id:null});if(!sources.at(-1).hash)throw new Error('生成素材文件不可用');}return {rendererVersion:2,name:w.name,work:input,sources};}
  async function begin(type,input){await B.requireConnection();if(!B.projectId)throw new Error('请先保存并打开项目');return B.request('/tasks',{method:'POST',data:{id:crypto.randomUUID(),projectId:B.projectId,type,input:JSON.parse(B.canonical(input))}});}
  const action=(id,action,extra={})=>B.request('/tasks/'+id+'/action',{method:'POST',data:{action,...extra}});
  async function result(task){const files=[];for(const id of task.outputMediaIds)files.push(await B.media(id));return files;}
  const abort=signal=>{if(signal?.aborted)throw new DOMException('已取消','AbortError');};
  async function wait(task,signal,progress){
    const cancel=()=>action(task.id,'cancel').catch(()=>{});signal?.addEventListener('abort',cancel,{once:true});
    try{while(true){abort(signal);task=await B.request('/tasks/'+task.id,{signal});progress?.(task.stage||'正在生成…',task.progress);if(task.state==='SUCCEEDED')return result(task);if(['FAILED','INTERRUPTED','CANCELLED'].includes(task.state))throw new Error(task.error||'任务已取消');await new Promise((resolve,reject)=>{const stop=()=>{clearTimeout(t);signal?.removeEventListener('abort',stop);reject(new DOMException('已取消','AbortError'));},t=setTimeout(()=>{signal?.removeEventListener('abort',stop);resolve();},1000);signal?.addEventListener('abort',stop,{once:true});});}}
    finally{signal?.removeEventListener('abort',cancel);}
  }
  async function submit(task,payload,signal,progress){abort(signal);const media=await B.upload(new File([payload],'input.zip',{type:'application/zip'}),{type:'bundle'});abort(signal);task=await action(task.id,'enqueue',{payloadMediaId:media.id});return (await wait(task,signal,progress))[0];}
  async function video(type,input,produce,signal,progress){const task=await begin(type,input);if(task.state==='SUCCEEDED'){progress?.('复用已生成的视频');return (await result(task))[0];}if(['QUEUED','RUNNING'].includes(task.state))return (await wait(task,signal,progress))[0];try{return await submit(task,await produce(),signal,progress);}catch(error){await action(task.id,error.name==='AbortError'?'cancel':'fail',{message:error.message}).catch(()=>{});throw error;}}
  const stateNames={PREPARING:'准备画面',QUEUED:'等待编码',RUNNING:'正在生成',CANCEL_REQUESTED:'正在取消',CANCELLED:'已取消',SUCCEEDED:'已完成',FAILED:'失败',INTERRUPTED:'处理已中断'};
  function mount(hooks){ui=hooks;document.getElementById('dialog').addEventListener('close',()=>{viewRevision++;clearTimeout(timer);});}
  async function open(){if(!B.connected){ui.toast('请先连接本地创作后台');return;}const token=++viewRevision;ui.modal('生成任务','<div id="creator-task-list">正在读取任务…</div>',[{label:'返回编辑',run:ui.close}]);await refresh(token);}
  async function refresh(token){if(token!==viewRevision)return;try{const tasks=await B.request('/tasks');if(token!==viewRevision||!document.getElementById('creator-task-list'))return;document.getElementById('creator-task-list').innerHTML=tasks.length?tasks.map(t=>'<article class="creator-task"><div><strong>'+esc(t.name||t.input?.name||({WALLPAPER_RENDER:'壁纸视频',CONTENT_RENDER:'视频作品',GALLERY_RENDER:'图片作品'}[t.type]))+'</strong><small>'+esc(stateNames[t.state]||t.state)+' · '+esc(t.stage||'')+'</small><p>'+esc(t.error||'')+'</p></div><div>'+(t.state==='SUCCEEDED'&&t.type!=='WALLPAPER_RENDER'?'<button data-task-save="'+t.id+'">保存至发布内容</button>':'')+(t.state==='SUCCEEDED'?'<button data-task-download="'+t.id+'">导出到本地</button>':'')+(['FAILED','INTERRUPTED'].includes(t.state)&&t.payloadMediaId?'<button data-task-retry="'+t.id+'">重试</button>':'')+(['PREPARING','QUEUED','RUNNING'].includes(t.state)?'<button data-task-cancel="'+t.id+'">取消</button>':'')+'</div></article>').join(''):'<p class="content-empty">还没有生成任务。</p>';for(const button of document.querySelectorAll('[data-task-download]'))button.onclick=async()=>{try{const task=tasks.find(t=>t.id===button.dataset.taskDownload);for(const file of await result(task))ui.download(file.name,file,file.type);}catch(error){ui.toast(error.message);}};for(const button of document.querySelectorAll('[data-task-save]'))button.onclick=async()=>{button.disabled=true;try{await ui.save(await B.request('/tasks/'+button.dataset.taskSave));}catch(error){ui.toast(error.message);button.disabled=false;}};for(const key of ['retry','cancel'])for(const button of document.querySelectorAll('[data-task-'+key+']'))button.onclick=async()=>{button.disabled=true;try{await action(button.dataset[key==='retry'?'taskRetry':'taskCancel'],key);await refresh(token);}catch(error){ui.toast(error.message);button.disabled=false;}};if(tasks.some(t=>['QUEUED','RUNNING','CANCEL_REQUESTED'].includes(t.state)))timer=setTimeout(()=>refresh(token),2000);}catch(error){if(token===viewRevision)ui.toast(error.message);}}
  window.CreatorJobs={snapshot,begin,action,result,wait,submit,video,mount,open};
})();
