/* MySQL-backed creator records; IndexedDB remains a recoverable editing cache. */
(() => {
  'use strict';
  const prefix='api/creator',versions=new Map(),fileIds=new WeakMap(),files=new Map(),uploads=new Map(),queues=new Map();
  let connected=false,projectId=null,ui={},connecting=null;
  const escape=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  function changed(){document.dispatchEvent(new CustomEvent('creator-connection',{detail:{connected}}));const button=document.getElementById('creator-connection');if(button){button.textContent=connected?'本地后台已连接':'连接本地后台';button.classList.toggle('save-error',!connected);}}
  async function request(path,{method='GET',data,body,headers={},signal}={}){
    let response;
    try{response=await fetch(prefix+path,{method,credentials:'same-origin',headers:{'X-Creator-Request':'1',...(data!==undefined?{'Content-Type':'application/json'}:{}),...headers},body:data!==undefined?JSON.stringify(data):body,signal});}
    catch(error){if(error.name==='AbortError')throw error;throw new Error('本地创作服务无法连接，请启动创作台');}
    if(!response.ok){const n=await response.json().catch(()=>({}));if(response.status===401){connected=false;changed();}const error=new Error(n.error||n.message||'创作数据未保存，请重试');error.status=response.status;throw error;}
    if(path.endsWith('/content'))return response.blob();return response.json();
  }
  async function ready(){const n=await request('/status');connected=!!n.connected;changed();return connected;}
  async function requireConnection(){if(!connected)throw new Error('请先连接本地后台，当前编辑内容保留在浏览器草稿中');}
  const canonical=value=>JSON.stringify(value,(_,v)=>v&&typeof v==='object'&&!Array.isArray(v)?Object.fromEntries(Object.keys(v).sort().map(k=>[k,v[k]])):v);
  async function hash(file){if(fileIds.has(file))return fileIds.get(file);const digest=await crypto.subtle.digest('SHA-256',await file.arrayBuffer()),id='file-'+Array.from(new Uint8Array(digest),v=>v.toString(16).padStart(2,'0')).join('');fileIds.set(file,id);return id;}
  function fileType(file,hint){if(hint&&['image','video','audio','4d','bundle'].includes(hint))return hint;const mime=file.type||'';return mime.startsWith('image/')?'image':mime.startsWith('video/')?'video':mime.startsWith('audio/')?'audio':'bundle';}
  async function upload(file,metadata={},fixedId){await requireConnection();const id=fixedId||await hash(file);if(uploads.has(id))return uploads.get(id);const promise=request('/media',{method:'POST',body:file,headers:{'Content-Type':'application/octet-stream','X-Media-Id':id,'X-Filename':encodeURIComponent(file.name||metadata.filename||'素材.zip'),'X-Media-Metadata':encodeURIComponent(JSON.stringify({...metadata,type:fileType(file,metadata.type)}))}}).then(n=>{files.set(id,file);return n;}).catch(error=>{uploads.delete(id);throw error;});uploads.set(id,promise);return promise;}
  async function media(id){if(files.has(id))return files.get(id);const n=await request('/media/'+id),blob=await request('/media/'+id+'/content'),file=new File([blob],n.filename,{type:n.mimeType});if(await hash(file)!=='file-'+n.sha256)throw new Error('素材文件校验不通过，请重新导入或恢复备份');files.set(id,file);return file;}
  async function pack(value,refs=new Set(),hint){
    if(value instanceof Blob){const n=await upload(value,{type:hint,filename:value.name});refs.add(n.id);return {$creatorFile:n.id};}
    if(Array.isArray(value)){const out=[];for(const row of value)out.push(await pack(row,refs,hint));return out;}
    if(value&&typeof value==='object'){const out={};for(const [key,row]of Object.entries(value)){if(key==='url'||key.startsWith('_creator')||row===undefined)continue;out[key]=await pack(row,refs,value.type||hint);}return out;}
    return value;
  }
  async function unpack(value){if(value?.$creatorFile)return media(value.$creatorFile);if(Array.isArray(value)){const out=[];for(const row of value)out.push(await unpack(row));return out;}if(value&&typeof value==='object'){const out={};for(const [key,row]of Object.entries(value))out[key]=await unpack(row);return out;}return value;}
  async function list(collection){await requireConnection();const rows=[];let cursor='';do{const page=await request('/records/'+collection+'?limit=1&after='+encodeURIComponent(cursor));rows.push(...page.items);cursor=page.nextCursor;}while(cursor);for(const row of rows)versions.set(collection+'/'+row.record.id,row.version);const result=[];for(const row of rows)result.push(await unpack(row.record));return result;}
  async function get(collection,id){await requireConnection();try{const row=await request('/records/'+collection+'/'+id);versions.set(collection+'/'+id,row.version);return unpack(row.record);}catch(error){if(error.status===404)return undefined;throw error;}}
  function put(collection,record){const key=collection+'/'+record.id;const operation=(queues.get(key)||Promise.resolve()).catch(()=>{}).then(async()=>{await requireConnection();if(!versions.has(key)){try{await get(collection,record.id);}catch(error){throw error;}}const refs=new Set(),payload=await pack(record,refs);const result=await request('/records/'+key,{method:'PUT',headers:{'If-Match':'"'+(versions.get(key)??0)+'"'},data:{record:payload,mediaIds:[...refs]}});versions.set(key,result.version);return record;});queues.set(key,operation);return operation;}
  async function migrate(collection,records){const existing=await list(collection),known=new Set(existing.map(r=>r.id));for(const record of records){if(known.has(record.id)&&!record._creatorPending)continue;let draft=record;if(known.has(record.id)){draft={...record,id:crypto.randomUUID(),name:record.name.slice(0,65)+' · 恢复草稿'};delete draft.deletedAt;if(collection==='projects'){draft.data={...draft.data,productRecord:null};draft.history=structuredClone(draft.history);for(const entry of draft.history?.entries||[])if(entry.data)entry.data.productRecord=null;}}await put(collection,draft);existing.push({...draft,_creatorPending:false});}return existing;}
  async function remove(collection,record){return put(collection,{...record,deletedAt:new Date().toISOString()});}
  function connect(){if(connecting)return connecting;connecting=new Promise(resolve=>{ui.modal('连接本地创作后台','<div class="content-template-form"><p>项目、素材、模板、收藏和作品保存在这台电脑的后台。请输入本地管理后台账号。</p><label>用户名<input id="creator-login-user" autocomplete="username"></label><label>密码<input id="creator-login-password" type="password" autocomplete="current-password"></label><p id="creator-login-error" role="alert"></p></div>',[{label:'继续编辑草稿',run:()=>{ui.close();resolve(false);}},{label:'连接并同步',primary:true,run:async()=>{const password=document.getElementById('creator-login-password'),button=document.querySelector('#dialog-actions .primary');if(button)button.disabled=true;try{await request('/connect',{method:'POST',data:{username:document.getElementById('creator-login-user').value.trim(),password:password.value}});password.value='';connected=true;changed();ui.close();resolve(true);}catch(error){document.getElementById('creator-login-error').textContent=error.message;if(button)button.disabled=false;}}}]);document.getElementById('dialog').addEventListener('close',()=>resolve(connected),{once:true});}).finally(()=>connecting=null);return connecting;}
  function mount(hooks){ui=hooks;const actions=document.querySelector('.project-actions')||document.getElementById('autosave-status')?.parentElement;if(actions){const button=document.createElement('button');button.id='creator-connection';button.textContent='连接本地后台';button.onclick=async()=>{await hooks.prepare?.();if(connected){ui.toast('项目和素材保存在本地后台；浏览器同时保留编辑草稿');return;}if(await connect())hooks.reopen();};actions.append(button);const tasks=document.createElement('button');tasks.id='creator-tasks';tasks.textContent='生成任务';tasks.onclick=()=>window.CreatorJobs.open();actions.append(tasks);const backup=document.createElement('button');backup.textContent='项目备份';backup.onclick=()=>hooks.backup();actions.append(backup);}changed();}
  window.CreatorBackend={request,ready,requireConnection,upload,media,hash,pack,unpack,canonical,list,get,put,migrate,remove,connect,mount,get connected(){return connected;},set projectId(id){projectId=id;},get projectId(){return projectId;},escape};
})();
