/* Canvas-only history, resizing and paints. No project state is restored here. */
(function(root){
  'use strict';
  const G=root.GalleryCore,C=root.ContentCore;
  const copy=C.copy;
  function snapshot(w){const gallery=copy(w.gallery);for(const key of ['view','selection','selectedSurface','surfaceSelection'])delete gallery[key];return {gallery,slots:copy(w.slots)};}
  function ensureHistory(w){if(!w.canvasHistory)w.canvasHistory={entries:[{label:'打开画布',data:snapshot(w)}],index:0};return w.canvasHistory;}
  function commit(w,label){const h=ensureHistory(w),data=snapshot(w);if(JSON.stringify(data)===JSON.stringify(h.entries[h.index].data))return false;h.entries=h.entries.slice(0,h.index+1);h.entries.push({label,data});if(h.entries.length>16)h.entries.shift();h.index=h.entries.length-1;return true;}
  function restore(w,redo=false){const h=ensureHistory(w),next=h.index+(redo?1:-1);if(next<0||next>=h.entries.length)return false;const {view,selection,selectedSurface,surfaceSelection}=w.gallery,data=copy(h.entries[next].data);w.gallery=data.gallery;w.slots=data.slots;w.gallery.view=view;w.gallery.selectedSurface=G.surface(w.gallery,selectedSurface)?selectedSurface:w.gallery.frames[0].id;G.refreshInstances(w.gallery);w.gallery.selection=(selection||[]).filter(id=>G.surfaces(w.gallery).some(f=>G.find(f.nodes,id)));w.gallery.surfaceSelection=(surfaceSelection||[]).filter(id=>G.surface(w.gallery,id));h.index=next;return true;}
  function resizeBox(before,edge,dx,dy,aspect=false){let left=edge.includes('w')?dx:0,top=edge.includes('n')?dy:0,width=Math.max(5,before.width+(edge.includes('e')?dx:0)-left),height=Math.max(5,before.height+(edge.includes('s')?dy:0)-top);if(aspect){if(edge==='n'||edge==='s')width=height/before.height*before.width;else height=width/before.width*before.height;}if(edge.includes('w'))left=before.width-width;if(edge.includes('n'))top=before.height-height;const center=G.point(G.transform(before),{x:left+width/2,y:top+height/2});return {x:center.x-width/2,y:center.y-height/2,width,height};}
  function scaleNodes(nodes,sx,sy){for(const n of nodes){n.x*=sx;n.y*=sy;n.width*=sx;n.height*=sy;if(n.fontSize)n.fontSize*=Math.min(sx,sy);if(n.letterSpacing)n.letterSpacing*=Math.min(sx,sy);if(n.radius)n.radius*=Math.min(sx,sy);if(n.children)scaleNodes(n.children,sx,sy);}}
  function resizeSurface(target,before,box,outerOnly=false){Object.assign(target,copy(before),box);if(outerOnly){for(const n of target.nodes){n.x+=before.x-box.x;n.y+=before.y-box.y;}}else scaleNodes(target.nodes,box.width/before.width,box.height/before.height);}
  function align(g,mode){let rows=G.roots(g).filter(r=>!r.node.locked);const frames=G.selectedSurfaces(g);if(!rows.length&&frames.length>1)rows=frames.map(f=>({node:f,matrix:G.transform(f),parentMatrix:G.identity,surface:{x:0,y:0}}));if(!rows.length)return false;const boxes=rows.map(r=>G.worldBounds(r)),f=G.surface(g),b=rows.length>1?G.union(boxes):{x:f.x,y:f.y,width:f.width,height:f.height};
    if(mode.startsWith('distribute')){if(rows.length<3)return false;const axis=mode==='distribute-x'?'x':'y',size=axis==='x'?'width':'height',order=rows.map((r,i)=>({r,b:boxes[i]})).sort((a,b)=>a.b[axis]-b.b[axis]),start=order[0].b[axis],last=order.at(-1).b,end=last[axis]+last[size],gap=(end-start-order.reduce((v,o)=>v+o.b[size],0))/(order.length-1);let position=start;for(const o of order){move(o.r,axis==='x'?position-o.b.x:0,axis==='y'?position-o.b.y:0);position+=o.b[size]+gap;}return true;}
    rows.forEach((r,i)=>{const box=boxes[i];let dx=0,dy=0;if(mode==='left')dx=b.x-box.x;if(mode==='center-x')dx=b.x+b.width/2-box.x-box.width/2;if(mode==='right')dx=b.x+b.width-box.x-box.width;if(mode==='top')dy=b.y-box.y;if(mode==='center-y')dy=b.y+b.height/2-box.y-box.height/2;if(mode==='bottom')dy=b.y+b.height-box.y-box.height;move(r,dx,dy);});return true;
    function move(r,dx,dy){const m=G.inverse(r.parentMatrix),p=G.point(m,{x:dx,y:dy}),origin=G.point(m,{x:0,y:0});r.node.x+=p.x-origin.x;r.node.y+=p.y-origin.y;}
  }
  function rgba(color,alpha=1){const m=/^#([0-9a-f]{6}|[0-9a-f]{3})$/i.exec(color||'');if(!m)return color||'#ffffff';const hex=m[1].length===3?m[1].split('').map(x=>x+x).join(''):m[1];return 'rgba('+[0,2,4].map(i=>parseInt(hex.slice(i,i+2),16)).join(',')+','+Math.max(0,Math.min(1,alpha))+')';}
  function paint(value){return typeof value==='object'&&value?(()=>{const p=copy(value);if(p.stops)p.stops.sort((a,b)=>a.offset-b.offset);return p;})():{type:'solid',color:value||'#ffffff',opacity:1,angle:90,stops:[{offset:0,color:value||'#ffffff',opacity:1},{offset:1,color:'#7c5cff',opacity:1}]};}
  function fill(ctx,value,width,height){if(typeof value!=='object'||!value)return value||'#ffffff';if(value.type==='solid')return rgba(value.color,value.opacity??1);let gradient;if(value.type==='radial'){gradient=ctx.createRadialGradient(width/2,height/2,0,width/2,height/2,Math.hypot(width,height)/2);}else{const a=(value.angle||0)*Math.PI/180,dx=Math.cos(a),dy=Math.sin(a),length=Math.abs(width*dx)+Math.abs(height*dy);gradient=ctx.createLinearGradient(width/2-dx*length/2,height/2-dy*length/2,width/2+dx*length/2,height/2+dy*length/2);}for(const stop of [...(value.stops||[])].sort((a,b)=>a.offset-b.offset))gradient.addColorStop(Math.max(0,Math.min(1,stop.offset)),rgba(stop.color,(stop.opacity??1)*(value.opacity??1)));return gradient;}
  function css(value){const p=paint(value);if(p.type==='solid')return rgba(p.color,p.opacity);const stops=p.stops.map(s=>rgba(s.color,(s.opacity??1)*(p.opacity??1))+' '+s.offset*100+'%').join(',');return p.type==='radial'?'radial-gradient(circle,'+stops+')':'linear-gradient('+(p.angle+90)+'deg,'+stops+')';}
  function fontFamily(name){return ({'system-ui':'-apple-system, BlinkMacSystemFont, "PingFang SC", sans-serif','sans-serif':'Arial, sans-serif',serif:'"Songti SC", "Times New Roman", serif',monospace:'Menlo, monospace'})[name]||JSON.stringify(name||'system-ui')+', sans-serif';}
  function textLayout(n,measure){const fontSize=n.fontSize||40,lineHeight=fontSize*(n.lineHeight||1.3),mode=n.textResize||'auto-height',lines=[];for(const line of String(n.text||'').split('\n')){let value='';for(const ch of line){if(mode!=='auto-width'&&value&&measure(value+ch)>n.width){lines.push(value);value=ch;}else value+=ch;}lines.push(value);}return {lines,width:mode==='auto-width'?Math.max(fontSize*.5,...lines.map(measure)):n.width,height:mode==='fixed'?n.height:Math.max(lineHeight,lines.length*lineHeight),lineHeight};}
  const api={snapshot,ensureHistory,commit,restore,resizeBox,resizeSurface,scaleNodes,align,paint,rgba,fill,css,fontFamily,textLayout};root.GalleryEditing=api;if(typeof module!=='undefined'&&module.exports)module.exports=api;
})(typeof window!=='undefined'?window:globalThis);
