/* Lightweight multi-frame editor. Media is shared; frame geometry and instance crops are local. */
(() => {
  'use strict';
  const G=window.GalleryCore,C=window.ContentCore,R=window.GalleryRenderer,E=window.GalleryEditing,P=window.GalleryProperties,$=id=>document.getElementById(id);
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  let H,canvas,ctx,viewport,observer,cache=new Map(),space=false,clipboard=null,drag=null,lastWork=null,editorInput=null,finishText=null,tool='select',hover=null,collapsed=new Set();
  const work=()=>H.work(),scene=()=>G.ensure(work()),surface=()=>G.surface(scene()),active=()=>H.active()&&work()?.type==='gallery';
  const change=label=>{G.captureOverrides(scene());H.change(label);},field=(label,key,value,type='number',extra='')=>'<label>'+label+'<input data-gallery-param="'+key+'" type="'+type+'" value="'+esc(value)+'" '+extra+'></label>';
  function mount(bridge){
    H=bridge;viewport=document.createElement('div');viewport.id='gallery-editor';
    viewport.innerHTML='<div class="gallery-tools"><div><button id="gallery-undo" title="撤销画布操作 ⌘/Ctrl Z" aria-label="撤销画布操作">↶</button><button id="gallery-redo" title="重做画布操作" aria-label="重做画布操作">↷</button><button data-gallery-tool="select" class="active" title="选择 V" aria-label="选择工具">↖ 选择</button><button id="gallery-add-frame" title="新建画框 F">▣ 画框</button><button id="gallery-add-text" title="文字 T" aria-label="文字工具">T 文字</button><button id="gallery-add-rect" title="矩形 R">□ 矩形</button></div><div><button id="gallery-group" title="分组 ⌘/Ctrl G">分组</button><button id="gallery-component" title="创建组件 ⌘/Ctrl Alt K">◇ 组件</button><button id="gallery-shortcuts" title="快捷键">⌨</button></div></div><div id="gallery-viewport"><canvas id="gallery-board" tabindex="0" aria-label="图片模板无限画布"></canvas><div id="gallery-selection-label"></div></div><div class="gallery-viewbar"><span id="gallery-canvas-status">空格拖动画布 · 滚轮平移 · ⌘/Ctrl + 滚轮缩放</span><div><button id="gallery-zoom-out" aria-label="缩小画布">−</button><button id="gallery-zoom-label">100%</button><button id="gallery-zoom-in" aria-label="放大画布">＋</button><button id="gallery-fit">适应画布</button></div></div>';
    $('content-canvas-area').after(viewport);canvas=$('gallery-board');ctx=canvas.getContext('2d');
    const inspector=document.createElement('div');inspector.id='gallery-inspector';inspector.className='content-inspector-scroll';document.querySelector('.content-inspector .panel-heading').after(inspector);
    observer=new ResizeObserver(()=>{if(active())draw();});observer.observe($('gallery-viewport'));bind();P.loadFonts(()=>{if(active()&&!editorInput)renderInspector();});
  }
  function render(){
    if(!active())return;const w=work(),g=scene();G.refreshInstances(g);if(lastWork!==w.id){lastWork=w.id;cache.clear();tool='select';document.querySelector('[data-gallery-tool="select"]').classList.add('active');$('gallery-add-text').classList.remove('active');}
    if(!w.canvasHistory){for(const f of G.surfaces(g))G.walk(f.nodes,n=>{if(n.type==='text')syncText(n);});E.ensureHistory(w);}if(!g.view)fit();renderInspector();draw();syncHistory();
  }
  function view(){return scene().view||{x:70,y:70,zoom:.25};}
  function frameRect(f){return {x:f.x,y:f.y,width:f.width,height:f.height};}
  function fit(selected=false){
    const g=scene(),frames=selected?(G.selectedSurfaces(g).length?G.selectedSurfaces(g):[surface()]):G.surfaces(g);if(!frames.length)return;const b=G.union(frames.map(frameRect)),rect=$('gallery-viewport').getBoundingClientRect(),z=C.clamp(Math.min((rect.width-100)/(b.width+60),(rect.height-90)/(b.height+60)),.025,4);
    g.view={x:(rect.width-b.width*z)/2-b.x*z,y:(rect.height-b.height*z)/2-b.y*z+12,zoom:z};H.save();draw();
  }
  function zoom(factor,anchor){const v=view(),r=$('gallery-viewport').getBoundingClientRect(),p=anchor||{x:r.width/2,y:r.height/2},before={x:(p.x-v.x)/v.zoom,y:(p.y-v.y)/v.zoom};v.zoom=C.clamp(v.zoom*factor,.025,6);v.x=p.x-before.x*v.zoom;v.y=p.y-before.y*v.zoom;scene().view=v;H.save();draw();}
  function world(e){const r=canvas.getBoundingClientRect(),v=view();return {x:(e.clientX-r.left-v.x)/v.zoom,y:(e.clientY-r.top-v.y)/v.zoom};}
  function cached(f){
    const w=work(),instancePreview={};G.walk(f.nodes,n=>{if(n.type==='instance'&&n.children)instancePreview[n.id]=C.copy(n.children);});const key=JSON.stringify([f,w.slots,w.gallery.components,instancePreview,editorInput?.nodeId]);let entry=cache.get(f.id);
    if(entry?.key===key)return entry;const prior=entry;entry={key,canvas:prior?.canvas,rect:prior?.rect};cache.set(f.id,entry);
    const target=document.createElement('canvas'),snapshot=C.copy(w),copy=C.copy(f);
    R.paint(target,snapshot,copy,H.resolve,{preview:true,instancePreview,hiddenId:f.id===gTextSurface()?editorInput?.nodeId:null}).then(rect=>{if(cache.get(f.id)===entry){entry.canvas=target;entry.rect=rect;if(active())draw();}}).catch(error=>{if(error.name!=='AbortError'&&cache.get(f.id)===entry){entry.error=error.message;H.toast('图片预览失败：'+error.message);}});
    return entry;
  }
  function gTextSurface(){return editorInput?.surfaceId;}
  function syncText(n){if(n.type!=='text')return;ctx.font=(n.fontWeight||400)+' '+(n.fontSize||40)+'px '+E.fontFamily(n.fontFamily);ctx.letterSpacing=(n.letterSpacing||0)+'px';const layout=E.textLayout(n,v=>ctx.measureText(v).width);n.width=layout.width;n.height=layout.height;}
  function selectionOutline(){const rows=G.roots(scene()),frames=G.selectedSurfaces(scene());if(!rows.length)return corners(frames.length?G.union(frames.map(frameRect)):frameRect(surface()));if(rows.length===1){const r=rows[0];return corners({x:0,y:0,width:r.node.width,height:r.node.height}).map(p=>{const q=G.point(r.matrix,p);return {x:q.x+r.surface.x,y:q.y+r.surface.y};});}return corners(G.union(rows.map(G.worldBounds)));}
  function corners(b){return [{x:b.x,y:b.y},{x:b.x+b.width,y:b.y},{x:b.x+b.width,y:b.y+b.height},{x:b.x,y:b.y+b.height}];}
  function handles(points){return points.map((p,i)=>({...p,edge:['nw','ne','se','sw'][i]}));}
  function edgeHit(p){if(editorInput||G.roots(scene()).length>1||G.selectedSurfaces(scene()).length>1)return null;const points=selectionOutline(),z=view().zoom;for(const h of handles(points))if(Math.hypot(h.x-p.x,h.y-p.y)<8/z)return h.edge;for(let i=0;i<4;i++){const a=points[i],b=points[(i+1)%4],length=(b.x-a.x)**2+(b.y-a.y)**2,t=Math.max(0,Math.min(1,((p.x-a.x)*(b.x-a.x)+(p.y-a.y)*(b.y-a.y))/length));if(Math.hypot(p.x-a.x-t*(b.x-a.x),p.y-a.y-t*(b.y-a.y))<5/z)return ['n','e','s','w'][i];}return null;}
  function resizeCursor(edge){const n=G.roots(scene())[0]?.node,angle=(n?.rotation||0)+(G.roots(scene())[0]?.parent?.rotation||0),base=({e:0,w:0,n:90,s:90,nw:45,se:45,ne:135,sw:135})[edge],directions=['ew-resize','nwse-resize','ns-resize','nesw-resize'];return directions[((Math.round((base+angle)/45)%4)+4)%4];}
  function syncHistory(){if(!active())return;const h=E.ensureHistory(work());$('gallery-undo').disabled=h.index===0;$('gallery-redo').disabled=h.index===h.entries.length-1;}
  function undo(redo=false){if(finishText)finishText(true);if(E.restore(work(),redo)){cache.clear();H.restored();}else H.toast(redo?'画布没有可重做的操作':'画布没有可撤销的操作');syncHistory();}
  function setTool(value){finishText?.(true);tool=value;space=false;canvas.style.cursor=value==='text'?'text':'default';document.querySelector('[data-gallery-tool="select"]').classList.toggle('active',value==='select');$('gallery-add-text').classList.toggle('active',value==='text');}
  function draw(){
    if(!active())return;const rect=$('gallery-viewport').getBoundingClientRect();if(rect.width<1||rect.height<1)return;const dpr=Math.min(devicePixelRatio||1,2);canvas.width=Math.round(rect.width*dpr);canvas.height=Math.round(rect.height*dpr);ctx.setTransform(dpr,0,0,dpr,0,0);ctx.letterSpacing='0px';
    ctx.fillStyle='#1e2024';ctx.fillRect(0,0,rect.width,rect.height);const v=view(),gap=24;ctx.fillStyle='#353a42';for(let x=((v.x%gap)+gap)%gap;x<rect.width;x+=gap)for(let y=((v.y%gap)+gap)%gap;y<rect.height;y+=gap)ctx.fillRect(x,y,1,1);
    ctx.save();ctx.translate(v.x,v.y);ctx.scale(v.zoom,v.zoom);
    const g=scene();for(const f of G.surfaces(g)){if(f.visible===false)continue;
      const component=!!g.components[f.id],entry=cached(f);ctx.fillStyle='#b2bbca';ctx.font=12/v.zoom+'px system-ui';ctx.textAlign='left';ctx.fillText((component?'◇ ':'▣ ')+f.name,f.x,f.y-13/v.zoom);
      ctx.fillStyle='#282c34';ctx.fillRect(f.x,f.y,f.width,f.height);
      if(entry.canvas){const b=entry.rect;ctx.save();ctx.globalAlpha=f.opacity??1;ctx.globalCompositeOperation=f.blendMode&&f.blendMode!=='pass-through'?f.blendMode:'source-over';ctx.drawImage(entry.canvas,f.x+b.x,f.y+b.y,b.width,b.height);ctx.restore();}
      ctx.strokeStyle=(g.surfaceSelection?.includes(f.id)||g.selectedSurface===f.id)?(component?'#bd92ff':'#80aaff'):'#515660';ctx.lineWidth=((g.surfaceSelection?.includes(f.id)||g.selectedSurface===f.id)?1.5:1)/v.zoom;ctx.strokeRect(f.x,f.y,f.width,f.height);
    }
    const points=selectionOutline();if(points&&!editorInput){ctx.strokeStyle='#92b8ff';ctx.lineWidth=1/v.zoom;ctx.beginPath();points.forEach((p,i)=>i?ctx.lineTo(p.x,p.y):ctx.moveTo(p.x,p.y));ctx.closePath();ctx.stroke();for(const p of handles(points)){ctx.fillStyle='#edf4ff';ctx.fillRect(p.x-3/v.zoom,p.y-3/v.zoom,6/v.zoom,6/v.zoom);ctx.strokeRect(p.x-3/v.zoom,p.y-3/v.zoom,6/v.zoom,6/v.zoom);}const n=G.roots(g)[0]?.node||surface(),bottom=points.reduce((m,p)=>Math.max(m,p.y),-Infinity),center=points.reduce((sum,p)=>sum+p.x,0)/4,label=(G.roots(g).length>1||G.selectedSurfaces(g).length>1)?Math.round(Math.max(...points.map(p=>p.x))-Math.min(...points.map(p=>p.x)))+' × '+Math.round(Math.max(...points.map(p=>p.y))-Math.min(...points.map(p=>p.y))):Math.round(n.width)+' × '+Math.round(n.height);ctx.font=10/v.zoom+'px system-ui';ctx.textAlign='center';ctx.fillStyle='#9fc2ff';ctx.fillText(label,center,bottom+17/v.zoom);}
    if(drag?.kind==='text-create'){const a=drag.p,b=drag.current;ctx.strokeStyle='#92b8ff';ctx.lineWidth=1/v.zoom;ctx.strokeRect(Math.min(a.x,b.x),Math.min(a.y,b.y),Math.abs(a.x-b.x),Math.abs(a.y-b.y));}
    if(drag?.kind==='marquee'){ctx.fillStyle='#80aaff20';ctx.strokeStyle='#82aaff';ctx.lineWidth=1/v.zoom;const b=drag.box;ctx.fillRect(b.x,b.y,b.width,b.height);ctx.strokeRect(b.x,b.y,b.width,b.height);}
    ctx.restore();$('gallery-zoom-label').textContent=Math.round(v.zoom*100)+'%';$('gallery-canvas-status').textContent=g.selection.length?g.selection.length+' 个图层 · 方向键微调 · Shift + 方向键移动 10 px':'空格拖动画布 · 滚轮平移 · ⌘/Ctrl + 滚轮缩放';
  }
  function select(f,n,shift=false,preserve=false){const g=scene();g.selectedSurface=f.id;if(n){g.surfaceSelection=[];if(shift)g.selection=g.selection.includes(n.id)?g.selection.filter(id=>id!==n.id):[...g.selection,n.id];else if(!preserve||!g.selection.includes(n.id))g.selection=[n.id];}else{g.selection=[];const ids=g.surfaceSelection||[];g.surfaceSelection=shift?(ids.includes(f.id)?ids.filter(id=>id!==f.id):[...ids,f.id]):[f.id];}H.save();H.library();renderInspector();draw();}
  const eyeIcon=visible=>'<svg viewBox="0 0 20 20" width="15" height="15" fill="none" stroke="currentColor" stroke-width="1.4" aria-hidden="true"><path d="M2 10s3-5 8-5 8 5 8 5-3 5-8 5-8-5-8-5Z"/><circle cx="10" cy="10" r="2"/>'+(visible?'':'<path d="M3 3l14 14"/>')+'</svg>';
  const lockIcon=locked=>'<svg viewBox="0 0 20 20" width="14" height="14" fill="none" stroke="currentColor" stroke-width="1.4" aria-hidden="true"><rect x="5" y="9" width="10" height="8" rx="1.5"/><path d="'+(locked?'M7 9V6a3 3 0 0 1 6 0v3':'M7 9V6a3 3 0 0 1 6 0')+'"/></svg>';
  const layerIcon=type=>({instance:'◇',group:'▧',text:'T',image:'▧',rect:'□',frame:'#'})[type]||'#';
  function renderLayers(){
    const g=scene();function rows(nodes,depth){return nodes.slice().reverse().map(n=>{const expandable=!!n.children?.length,folded=collapsed.has(n.id);return '<div class="gallery-layer-row'+(g.selection.includes(n.id)?' selected':'')+(n.visible===false?' hidden-layer':'')+'" style="--layer-depth:'+depth+'"><button class="gallery-layer-toggle" data-layer-collapse="'+n.id+'" aria-label="'+(folded?'展开':'折叠')+' '+esc(n.name)+'"'+(!expandable?' disabled':'')+'>'+ (expandable?(folded?'›':'⌄'):'')+'</button><button class="gallery-layer-name" data-gallery-select="'+n.id+'" title="'+esc(n.name)+'"><span class="gallery-layer-icon '+(n.type==='instance'?'component-icon':'')+'">'+layerIcon(n.type)+'</span><span>'+esc(n.name)+'</span></button><button class="gallery-layer-action'+(n.locked?' on':'')+'" data-gallery-lock="'+n.id+'" aria-label="锁定或解锁 '+esc(n.name)+'">'+lockIcon(n.locked)+'</button><button class="gallery-layer-action'+(n.visible===false?' on':'')+'" data-gallery-visible="'+n.id+'" aria-label="显示或隐藏 '+esc(n.name)+'">'+eyeIcon(n.visible!==false)+'</button></div>'+(expandable&&!folded?rows(n.children,depth+1):'');}).join('');}
    return '<div class="gallery-layer-list">'+G.surfaces(g).map(f=>'<div class="gallery-frame-tree"><div class="gallery-layer-row gallery-frame-row'+((g.surfaceSelection?.includes(f.id)||(!g.selection.length&&g.selectedSurface===f.id))?' selected':'')+'"><button class="gallery-layer-toggle" data-layer-collapse="'+f.id+'" aria-label="'+(collapsed.has(f.id)?'展开':'折叠')+' '+esc(f.name)+'">'+(collapsed.has(f.id)?'›':'⌄')+'</button><button class="gallery-layer-name" data-gallery-surface="'+f.id+'"><span class="gallery-layer-icon '+(g.components[f.id]?'component-icon':'')+'">'+(g.components[f.id]?'◇':'#')+'</span><span>'+esc(f.name)+'</span></button><button class="gallery-layer-action'+(f.locked?' on':'')+'" data-surface-lock="'+f.id+'" aria-label="锁定或解锁画框 '+esc(f.name)+'">'+lockIcon(f.locked)+'</button><button class="gallery-layer-action'+(f.visible===false?' on':'')+'" data-surface-visible="'+f.id+'" aria-label="显示或隐藏画框 '+esc(f.name)+'">'+eyeIcon(f.visible!==false)+'</button></div>'+(!collapsed.has(f.id)?rows(f.nodes,1):'')+'</div>').join('')+'</div>';
  }
  function renderComponents(){return '<p class="content-slot-help">主组件的修改会同步到实例。双击实例可在当前画面内编辑，并独立保留修改。</p>'+Object.values(scene().components).map(c=>'<div class="gallery-component-card"><button data-gallery-surface="'+c.id+'">◇ '+esc(c.name)+'</button><small>'+G.instances(scene(),c.id).length+' 个实例</small><button data-gallery-insert="'+c.id+'">＋ 添加实例</button></div>').join('');}
  function bindLibrary(){
    document.querySelectorAll('[data-gallery-surface]').forEach(b=>b.onclick=e=>{select(G.surface(scene(),b.dataset.gallerySurface),null,e.shiftKey);});
    document.querySelectorAll('[data-gallery-select]').forEach(b=>b.onclick=e=>{const f=G.surfaces(scene()).find(f=>G.find(f.nodes,b.dataset.gallerySelect));select(f,G.find(f.nodes,b.dataset.gallerySelect).node,e.shiftKey);});
    document.querySelectorAll('[data-layer-collapse]').forEach(b=>b.onclick=()=>{const id=b.dataset.layerCollapse;collapsed.has(id)?collapsed.delete(id):collapsed.add(id);H.library();});
    for(const [attr,key] of [['galleryVisible','visible'],['galleryLock','locked']])document.querySelectorAll('[data-'+attr.replace(/[A-Z]/g,c=>'-'+c.toLowerCase())+']').forEach(b=>b.onclick=()=>{const f=G.surfaces(scene()).find(f=>G.find(f.nodes,b.dataset[attr])),n=G.find(f.nodes,b.dataset[attr]).node;n[key]=key==='visible'?n[key]===false:!n[key];change(key==='visible'?'切换图层显示':'切换图层锁定');});
    for(const [attr,key] of [['surfaceVisible','visible'],['surfaceLock','locked']])document.querySelectorAll('[data-'+attr.replace(/[A-Z]/g,c=>'-'+c.toLowerCase())+']').forEach(b=>b.onclick=()=>{const f=G.surface(scene(),b.dataset[attr]);f[key]=key==='visible'?f[key]===false:!f[key];change('切换画框'+(key==='visible'?'显示':'锁定'));});
    document.querySelectorAll('[data-gallery-insert]').forEach(b=>b.onclick=()=>{if(!G.addInstance(scene(),b.dataset.galleryInsert))H.toast('不能将组件放入自身或它依赖的组件');else{scene().surfaceSelection=[];change('添加组件实例');}});
  }
  function sourceOptions(value){return '<option value="">未绑定</option><option value="slot:wallpaper"'+(value==='slot:wallpaper'?' selected':'')+'>主壁纸 · 项目素材</option>'+H.sources().filter(a=>a.type==='image').map(a=>'<option value="'+a.id+'"'+(a.id===value?' selected':'')+'>'+esc(a.name)+'</option>').join('');}
  function renderInspector(){
    if(!active())return;const g=scene(),f=surface(),rows=G.selected(g),n=rows[0]?.node,component=!!g.components[f.id];let html='';
    if(!n&&G.selectedSurfaces(g).length>1){html='<section><div class="section-title"><strong>'+G.selectedSurfaces(g).length+' 个画框</strong></div>'+P.alignControls()+'<p class="content-slot-help">Shift 点击画框可多选，一起移动、复制或对齐。</p></section>'+P.appearance(f,true);}else if(!n){
      html='<section><div class="section-title"><strong>'+(component?'◇ 主组件':'▣ 画框')+'</strong><span>'+g.frames.length+' 张图片</span></div>'+field('名称','name',f.name,'text')+'<div class="two-fields">'+field('宽度 px','width',f.width)+field('高度 px','height',f.height)+'</div>';
      if(!component)html+='<label>尺寸预设<select id="gallery-size-preset"><option value="">选择尺寸</option><option value="1080x1440">3:4 · 1080 × 1440</option><option value="1080x1920">9:16 · 1080 × 1920</option><option value="1080x1080">1:1 · 1080 × 1080</option><option value="1206x2622">iPhone · 1206 × 2622</option></select></label><button id="gallery-size-all" class="full-width">将此尺寸应用到全部画框</button><label class="gallery-check"><input id="gallery-clip" type="checkbox" '+(f.clip?'checked':'')+'>裁剪溢出内容</label><p class="content-slot-help">关闭后可在画布查看溢出部分；导出的图片仍以画框尺寸为边界。</p>'+P.paintControl('背景颜色','background',f.background||'#18202c');
      if(component)html+='<label class="gallery-check"><input id="gallery-clip" type="checkbox" '+(f.clip!==false?'checked':'')+'>裁剪溢出内容</label>';html+='</section>'+P.appearance(f,true)+'<section><div class="gallery-action-grid"><button id="gallery-copy-frame">复制'+(component?'组件':'画框')+'</button><button id="gallery-remove-frame">删除'+(component?'组件':'画框')+'</button></div>';
      if(!component)html+='<div class="gallery-action-grid"><button id="gallery-frame-prev">导出顺序前移</button><button id="gallery-frame-next">导出顺序后移</button></div>';
      else html+=P.paintControl('背景颜色','background',f.background||'#282c34')+'<p class="content-slot-help">这里的图层是主组件。选中图片后替换素材，会更新所有实例。</p>';
      html+='</section>';
    }else{
      html='<section><div class="section-title"><strong>'+(rows.length>1?rows.length+' 个图层':n.type==='instance'?'◇ 组件实例':'图层属性')+'</strong><button id="gallery-select-frame" class="text-button">画框</button></div>'+P.alignControls()+field('名称','name',n.name,'text')+'<div class="two-fields">'+field('X','x',Math.round(n.x))+field('Y','y',Math.round(n.y))+'</div><div class="two-fields">'+field('宽度 px','width',Math.round(n.width))+field('高度 px','height',Math.round(n.height))+'</div><div class="two-fields">'+field('旋转 °','rotation',n.rotation||0)+'</div><div class="gallery-action-grid"><button id="gallery-layer-up">上移一层 ]</button><button id="gallery-layer-down">下移一层 [</button></div></section>';
      html+=P.appearance(n,['group','instance'].includes(n.type));
      if(n.type==='text')html+='<section><label>文字内容<textarea id="gallery-text" rows="4">'+esc(n.text)+'</textarea></label>'+P.fontControl(n.fontFamily)+'<div class="two-fields">'+field('字号','fontSize',n.fontSize||40)+'<label>字重<select data-gallery-param="fontWeight"><option value="400">常规</option><option value="600">中粗</option><option value="700">粗体</option></select></label></div>'+'<label>文本框<select data-gallery-param="textResize"><option value="auto-width">自动宽度</option><option value="auto-height">自动高度</option><option value="fixed">固定尺寸</option></select></label>'+P.textAlignControls(n)+'<div class="two-fields">'+field('行高倍数','lineHeight',n.lineHeight||1.3,'number','min="0.5" max="5" step="0.05"')+field('字距 px','letterSpacing',n.letterSpacing||0)+'</div>'+P.paintControl('文字颜色','color',n.color||'#ffffff')+'</section>';
      if(n.type==='image')html+='<section><label>图片素材<select id="gallery-image-source">'+sourceOptions(n.slot?'slot:'+n.slot:n.assetId)+'</select></label><label>填充方式<select data-gallery-param="fit"><option value="cover">填满 · 裁剪</option><option value="contain">完整显示</option></select></label></section>';
      if(n.type==='instance')html+='<section><div class="section-title"><strong>'+esc(g.components[n.componentId]?.name||'组件')+'</strong></div><button id="gallery-edit-instance" class="full-width">编辑当前画面的组件</button><button id="gallery-reset-instance" class="full-width">重置当前实例修改</button><label class="gallery-check"><input id="gallery-instance-clip" type="checkbox" '+((n.clip??g.components[n.componentId]?.clip)!==false?'checked':'')+'>裁剪溢出内容</label><button id="gallery-detach" class="full-width">解除组件关联</button><label>蒙版样式<select data-gallery-param="mask"><option value="none">无</option><option value="round">圆角屏幕</option><option value="phone">手机样机</option></select></label></section>';
      if(['image','instance'].includes(n.type))html+='<section><div class="section-title"><strong>图片构图</strong></div>'+field('内容缩放','scale',n.scale||1,'number','min="0.1" max="10" step="0.1"')+'<div class="two-fields">'+field('水平偏移 %','panX',n.panX||0)+field('垂直偏移 %','panY',n.panY||0)+'</div>'+'</section>';
      if(n.type==='rect')html+='<section>'+P.paintControl('填充颜色','color',n.color||'#ffffff')+'</section>';
      html+='<section><div class="gallery-action-grid"><button id="gallery-selection-group">分组</button><button id="gallery-ungroup">取消分组</button><button id="gallery-create-component">创建组件</button><button id="gallery-delete">删除图层</button></div></section>';
    }
    $('gallery-inspector').innerHTML=html;bindInspector(n||f,!!n);
  }
  function action(id,fn){if($(id))$(id).onclick=fn;}
  function bindInspector(target,isNode){
    P.bindPaint(target,change,draw);P.bindFont(target,change,syncText);document.querySelectorAll('[data-gallery-align]').forEach(b=>b.onclick=()=>{if(E.align(scene(),b.dataset.galleryAlign))change('对齐画布图层');else H.toast('分布需要选择至少三个图层');});
    document.querySelectorAll('[data-gallery-param]').forEach(input=>{const key=input.dataset.galleryParam;if(input.tagName==='SELECT')input.value=target[key]??({textResize:'auto-height',verticalAlign:'top'}[key]||input.value);input.onchange=()=>{let value=input.type==='number'?input.valueAsNumber:input.value;if(input.type==='number'&&!Number.isFinite(value))return renderInspector();if(['width','height'].includes(key))value=C.clamp(value,1,isNode?16000:4096);if(key==='fontSize')value=C.clamp(value,1,1000);if(key==='opacity')value=C.clamp(value/100,0,1);if(key==='scale')value=C.clamp(value,.1,10);if(key==='radius')value=Math.max(0,value);if(['opacity','blendMode','radius'].includes(key)){const targets=isNode?G.roots(scene()).map(r=>r.node):G.selectedSurfaces(scene());targets.forEach(n=>n[key]=value);}if(key==='fontWeight')value=Number(value);if(isNode&&target.type==='group'&&['width','height'].includes(key))G.resizeGroup(target,key==='width'?value:target.width,key==='height'?value:target.height);else target[key]=value;if(isNode&&target.type==='text'){if(key==='width'&&target.textResize==='auto-width')target.textResize='auto-height';if(key==='height')target.textResize='fixed';syncText(target);}change('修改'+(isNode?'图层':'画框')+'属性');};});
    document.querySelectorAll('[data-text-alignment]').forEach(b=>b.onclick=()=>{target[b.dataset.textAlignment]=b.dataset.textAlignValue;change('设置文字对齐');});
    action('gallery-select-frame',()=>select(surface(),null));action('gallery-size-all',()=>{const f=surface();for(const s of scene().frames){s.width=f.width;s.height=f.height;}scene().preset={width:f.width,height:f.height};change('统一画框尺寸');});
    if($('gallery-size-preset'))$('gallery-size-preset').onchange=e=>{if(!e.target.value)return;const [width,height]=e.target.value.split('x').map(Number);Object.assign(surface(),{width,height});scene().preset={width,height};change('设置画框尺寸');};
    if($('gallery-clip'))$('gallery-clip').onchange=e=>{surface().clip=e.target.checked;change('切换画框溢出裁剪');};
    if($('gallery-text'))$('gallery-text').onchange=e=>{target.text=e.target.value;syncText(target);change('编辑文字');};
    if($('gallery-image-source'))$('gallery-image-source').onchange=e=>{const value=e.target.value;target.slot=value==='slot:wallpaper'?'wallpaper':null;target.assetId=target.slot?null:value||null;change('替换组件或图层图片');};
    action('gallery-copy-frame',copyFrame);action('gallery-remove-frame',removeSurface);
    for(const [id,d] of [['gallery-frame-prev',-1],['gallery-frame-next',1]])action(id,()=>{const g=scene(),index=g.frames.indexOf(surface()),next=index+d;if(next<0||next>=g.frames.length)return;g.frames.splice(next,0,g.frames.splice(index,1)[0]);change('调整图集导出顺序');});
    action('gallery-layer-up',()=>reorder(1));action('gallery-layer-down',()=>reorder(-1));action('gallery-selection-group',group);action('gallery-ungroup',ungroup);action('gallery-create-component',component);action('gallery-delete',remove);
    action('gallery-edit-instance',()=>editInstance(target));action('gallery-reset-instance',()=>{delete target.overrides;delete target.localNodes;change('重置当前组件实例');});if($('gallery-instance-clip'))$('gallery-instance-clip').onchange=e=>{target.clip=e.target.checked;change('修改组件溢出裁剪');};
    action('gallery-detach',()=>{const def=scene().components[target.componentId],r=G.find(surface().nodes,target.id);if(!def)return;const group=G.node('group',{x:target.x,y:target.y,width:def.width,height:def.height,name:target.name,rotation:target.rotation,opacity:target.opacity,children:def.nodes.map(G.cloneNode),mask:target.mask,scale:target.scale,panX:target.panX,panY:target.panY,radius:target.radius,lock:target.lock});G.resizeGroup(group,target.width,target.height);r.list.splice(r.list.indexOf(target),1,group);scene().selection=[group.id];change('解除组件关联');});
  }
  function addFrame(){const g=scene(),f=G.frame(g.preset.width,g.preset.height,g.frames.length),last=g.frames.at(-1);if(last){f.x=last.x+last.width+180;f.y=last.y;}g.frames.push(f);g.selectedSurface=f.id;g.selection=[];g.surfaceSelection=[f.id];change('新增画框');fit(true);}
  function add(type){const f=surface(),n=G.node(type,{x:f.width*.15,y:f.height*.15,width:type==='text'?f.width*.7:Math.min(360,f.width*.5),height:type==='text'?120:Math.min(360,f.height*.5),text:'双击编辑文字',fontSize:48,fontFamily:'system-ui',fontWeight:400,color:type==='text'?'#ffffff':'#6c92ce',align:'left'});f.nodes.push(n);scene().selection=[n.id];scene().surfaceSelection=[];change(type==='text'?'新增文字':'新增矩形');}
  function addAsset(asset,position=null){if(asset.type!=='image'){H.toast('图片模板请使用图片或透明样机图片');return;}const f=surface(),width=Math.min(asset.width||f.width,f.width*.8),height=width/(asset.width||1)*(asset.height||1),n=G.node('image',{name:asset.name,assetId:asset.id,width,height,x:(f.width-width)/2,y:(f.height-height)/2,fit:'contain'});if(position){n.x=Math.round(position.x-f.x-width/2);n.y=Math.round(position.y-f.y-height/2);}f.nodes.push(n);scene().selection=[n.id];change('加入图片素材');}
  function group(){if(!G.group(scene()))return H.toast('请选择同一分组下的两个或更多图层');change('图层分组');}
  function ungroup(){if(G.ungroup(scene()))change('取消分组');}
  function component(){const def=G.makeComponent(scene());if(!def)return H.toast('先选择图片、文字或分组');change('创建主组件');H.showLibrary('components');}
  function editInstance(n,point=null){const f=G.selected(scene()).find(r=>r.node===n)?.surface||surface(),r=G.find(f.nodes,n.id);if(!r||!n.children?.length)return;const local=point?G.point(G.inverse(r.matrix),{x:point.x-f.x,y:point.y-f.y}):null,child=local?G.hit(n.children,local,true):n.children.find(c=>c.visible!==false);if(child){collapsed.delete(n.id);select(f,child);H.showLibrary('layers');if(child.type==='text'&&point)inlineText(child);}}
  const frameSelection=()=>G.selectedSurfaces(scene()).length?G.selectedSurfaces(scene()):[surface()];
  function insertFrames(sources){const g=scene(),bounds=G.union(sources.map(frameRect)),ids=[];for(const source of sources){const n=C.copy(source);n.id=C.id();n.name+=' 副本';n.x+=bounds.width+180;n.nodes=n.nodes.map(G.cloneNode);if(g.components[source.id])g.components[n.id]=n;else g.frames.push(n);ids.push(n.id);}g.selectedSurface=ids.at(-1);g.surfaceSelection=ids;g.selection=[];}
  function copyFrame(){insertFrames(frameSelection());change('复制画框或组件');}
  function removeSurface(){const g=scene(),frames=frameSelection(),ids=new Set(frames.map(f=>f.id));if(g.frames.every(f=>ids.has(f.id)))return H.toast('至少保留一个画框');if(frames.some(f=>g.components[f.id]&&G.instances(g,f.id).length))return H.toast('该组件仍有实例，请先解除实例关联');for(const f of frames)if(g.components[f.id])delete g.components[f.id];g.frames=g.frames.filter(f=>!ids.has(f.id));g.selectedSurface=g.frames[0].id;g.selection=[];g.surfaceSelection=[];change('删除画框或组件');}
  function remove(){if(scene().selection.length){G.remove(scene());change('删除图层');}else removeSurface();}
  function reorder(direction){const rows=G.roots(scene());if(rows.length!==1)return H.toast('先选择一个图层或分组');const r=rows[0],index=r.list.indexOf(r.node),next=index+direction;if(next<0||next>=r.list.length)return;r.list.splice(next,0,r.list.splice(index,1)[0]);change('调整图层顺序');}
  function copySelection(cut=false){const g=scene(),rows=G.roots(g);clipboard={project:H.projectId(),nodes:rows.map(r=>C.copy(r.node)),surfaces:rows.length?null:frameSelection().map(C.copy),components:C.copy(g.components)};if(cut)remove();else H.toast(rows.length?'已复制图层':'已复制画框');}
  function paste(){if(!clipboard)return;if(clipboard.project!==H.projectId())return H.toast('请在当前项目重新复制图层');const g=scene();for(const [key,def] of Object.entries(clipboard.components))if(!g.components[key])g.components[key]=C.copy(def);if(clipboard.surfaces)insertFrames(clipboard.surfaces);else{const f=surface(),nodes=clipboard.nodes.filter(n=>!n.componentId||!G.wouldCycle(g,f.id,n.componentId)).map(G.cloneNode);nodes.forEach(n=>{n.x+=32;n.y+=32;});f.nodes.push(...nodes);g.selection=nodes.map(n=>n.id);g.surfaceSelection=[];}change('粘贴图层或画框');}
  function inlineText(n,created=false){
    if(n.type!=='text')return;finishText?.(true);const before=C.copy(n),f=G.selected(scene()).find(r=>r.node===n)?.surface||surface(),r=G.find(f.nodes,n.id),m=r.matrix,v=view(),input=document.createElement('textarea');editorInput=input;input.nodeId=n.id;input.surfaceId=f.id;input.className='gallery-inline-text';input.value=n.text;input.spellcheck=false;const origin=G.point(m,{x:0,y:0}),angle=Math.atan2(m[1],m[0]);const padding=()=>{ctx.font=(n.fontWeight||400)+' '+n.fontSize+'px '+E.fontFamily(n.fontFamily);ctx.letterSpacing=(n.letterSpacing||0)+'px';const height=E.textLayout(n,value=>ctx.measureText(value).width).lines.length*n.fontSize*(n.lineHeight||1.3);return Math.max(0,n.height-height)*(n.verticalAlign==='center'?.5:n.verticalAlign==='bottom'?1:0)*v.zoom;};Object.assign(input.style,{left:(f.x+origin.x)*v.zoom+v.x+'px',top:(f.y+origin.y)*v.zoom+v.y+'px',width:Math.max(n.width*v.zoom,10)+'px',height:Math.max(n.height*v.zoom,10)+'px',fontSize:n.fontSize*v.zoom+'px',fontFamily:E.fontFamily(n.fontFamily),fontWeight:n.fontWeight||400,lineHeight:n.lineHeight||1.3,letterSpacing:(n.letterSpacing||0)*v.zoom+'px',textAlign:n.align||'left',color:typeof n.color==='string'?n.color:E.paint(n.color).color,transform:'rotate('+angle+'rad)',transformOrigin:'0 0',whiteSpace:n.textResize==='auto-width'?'pre':'pre-wrap',paddingTop:padding()+'px'});input.wrap=n.textResize==='auto-width'?'off':'soft';$('gallery-viewport').append(input);input.focus();if(!created)input.select();let done=false;
    finishText=save=>{if(done)return;done=true;const value=input.value;input.remove();editorInput=null;finishText=null;if(!save){if(created)r.list.splice(r.list.indexOf(n),1);else Object.assign(n,before);}else if(created&&!value.trim()){r.list.splice(r.list.indexOf(n),1);scene().selection=[];}else{n.text=value;syncText(n);if(created||JSON.stringify(before)!==JSON.stringify(n))change(created?'新增文字':'编辑文字');}cache.clear();renderInspector();draw();};
    input.oninput=()=>{n.text=input.value;syncText(n);input.style.width=Math.max(10,n.width*v.zoom)+'px';input.style.height=Math.max(10,n.height*v.zoom)+'px';input.style.paddingTop=padding()+'px';draw();};input.onblur=()=>finishText?.(true);input.onkeydown=e=>{if(e.key==='Escape'){e.preventDefault();finishText(false);}else if((e.metaKey||e.ctrlKey)&&e.key==='Enter'){e.preventDefault();finishText(true);}};draw();
  }
  function createText(position,box=null){const f=surface(),n=G.node('text',{x:position.x-f.x,y:position.y-f.y,width:box?.width||200,height:box?.height||65,text:'',name:'文字',fontSize:48,fontFamily:'system-ui',fontWeight:400,color:'#ffffff',align:'left',verticalAlign:'top',textResize:box?'fixed':'auto-width',lineHeight:1.3});f.nodes.push(n);scene().selection=[n.id];if(!box)syncText(n);tool='select';document.querySelector('[data-gallery-tool="select"]').classList.add('active');$('gallery-add-text').classList.remove('active');H.library();renderInspector();inlineText(n,true);}
  function bind(){
    document.querySelector('[data-gallery-tool="select"]').onclick=()=>{setTool('select');canvas.focus();};action('gallery-undo',()=>undo());action('gallery-redo',()=>undo(true));
    action('gallery-add-frame',addFrame);action('gallery-add-text',()=>setTool('text'));action('gallery-add-rect',()=>add('rect'));action('gallery-group',group);action('gallery-component',component);action('gallery-zoom-in',()=>zoom(1.25));action('gallery-zoom-out',()=>zoom(.8));action('gallery-fit',()=>fit());action('gallery-zoom-label',()=>fit(true));
    action('gallery-shortcuts',()=>H.modal('图片模板快捷键','<div class="gallery-shortcut-list"><p>⌘ / Ctrl + C / X / V　复制 / 剪切 / 粘贴</p><p>⌘ / Ctrl + D　创建副本</p><p>⌘ / Ctrl + Z　撤销　·　⌘ / Ctrl + Shift + Z / Ctrl + Y　重做</p><p>⌘ / Ctrl + G　分组　·　⌘ / Ctrl + Shift + G　取消分组</p><p>⌘ / Ctrl + Alt + K　创建组件</p><p>Delete / Backspace　删除　·　[ / ]　调整图层顺序</p><p>方向键　移动 1 px　·　Shift + 方向键　移动 10 px</p><p>空格 + 拖动 / 中键　平移画布</p><p>⌘ / Ctrl + 滚轮 / ＋ / −　缩放</p><p>Shift + 1　查看全部画框　·　Shift + 2　查看当前画框</p><p>V　选择　·　F　新建画框　·　T　文字　·　R　矩形</p><p>Shift + 点击　多选元素或画框　·　Alt + 点击　选择组内图层</p><p>T + 点击　创建文字　·　T + 拖动　创建文本框</p><p>双击文字　编辑内容　·　F2　重命名</p><p>拖动画框边角　缩放内容　·　⌘ / Ctrl + 拖动　只改外框</p><p>画布撤销与重做独立保留最近 15 步。</p></div>',[{label:'知道了',primary:true,run:H.close}]));
    canvas.onwheel=e=>{e.preventDefault();if(e.ctrlKey||e.metaKey){const r=canvas.getBoundingClientRect();zoom(Math.exp(-e.deltaY*.003),{x:e.clientX-r.left,y:e.clientY-r.top});}else{view().x-=e.deltaX;view().y-=e.deltaY;H.save();draw();}};
    canvas.oncontextmenu=e=>e.preventDefault();
    canvas.onpointerdown=e=>{
      if(!active()||e.button===2)return;finishText?.(true);e.preventDefault();canvas.focus();canvas.setPointerCapture(e.pointerId);const p=world(e),g=scene(),v=view();
      if(space||e.button===1){drag={kind:'pan',x:e.clientX,y:e.clientY,view:{...v}};canvas.style.cursor='grabbing';return;}
      if(tool==='text'){const f=G.surfaces(g).slice().reverse().find(f=>p.x>=f.x&&p.x<=f.x+f.width&&p.y>=f.y&&p.y<=f.y+f.height);if(!f){H.toast('在画框内点击或拖动，添加文字');return;}const n=G.hit(f.nodes,{x:p.x-f.x,y:p.y-f.y},true);if(n?.type==='text'){select(f,n);setTool('select');inlineText(n);return;}select(f,null);drag={kind:'text-create',p,current:p};return;}
      const edge=edgeHit(p),rows=G.roots(g);if(!e.shiftKey&&edge&&(rows.length?!rows[0].node.locked:!surface().locked)){drag=rows.length?{kind:'resize',p,edge,row:rows[0],before:C.copy(rows[0].node)}:{kind:'surface-resize',p,edge,f:surface(),before:C.copy(surface()),outerOnly:e.metaKey||e.ctrlKey};canvas.style.cursor=resizeCursor(edge);return;}
      for(const f of G.surfaces(g).slice().reverse()){if(f.visible===false||f.locked)continue;
        const inFrame=p.x>=f.x&&p.x<=f.x+f.width&&p.y>=f.y&&p.y<=f.y+f.height,title=p.x>=f.x&&p.x<=f.x+f.width&&p.y<f.y&&p.y>=f.y-30/v.zoom,hit=(!f.clip||inFrame)?G.hit(f.nodes,{x:p.x-f.x,y:p.y-f.y},e.altKey):null;
        if(title){if(!e.shiftKey&&g.surfaceSelection?.includes(f.id)&&g.surfaceSelection.length>1){g.selectedSurface=f.id;}else select(f,null,e.shiftKey);drag={kind:'frames',p,frames:frameSelection().filter(f=>!f.locked).map(f=>({f,before:{x:f.x,y:f.y}}))};return;}
        if(hit){select(f,hit,e.shiftKey,true);drag={kind:'nodes',p,rows:G.roots(g).filter(r=>!r.node.locked).map(r=>({...r,before:C.copy(r.node)}))};canvas.style.cursor='move';return;}
        if(inFrame){select(f,null,e.shiftKey);drag=e.shiftKey?{kind:'frames',p,frames:frameSelection().filter(f=>!f.locked).map(f=>({f,before:{x:f.x,y:f.y}}))}:{kind:'marquee',p,box:{x:p.x,y:p.y,width:0,height:0},base:[],baseFrames:[]};return;}
      }
      if(!e.shiftKey){g.selection=[];g.surfaceSelection=[];}drag={kind:'marquee',p,box:{x:p.x,y:p.y,width:0,height:0},base:e.shiftKey?[...g.selection]:[],baseFrames:e.shiftKey?[...(g.surfaceSelection||[])]:[]};renderInspector();draw();
    };
    canvas.onpointermove=e=>{
      if(!active())return;const p=world(e);if(!drag){hover=edgeHit(p);canvas.style.cursor=space?'grab':tool==='text'?'text':hover?resizeCursor(hover):'default';return;}const dx=p.x-drag.p?.x,dy=p.y-drag.p?.y;
      if(drag.kind==='pan'){view().x=drag.view.x+e.clientX-drag.x;view().y=drag.view.y+e.clientY-drag.y;}
      if(drag.kind==='text-create')drag.current=p;
      if(drag.kind==='frames')for(const {f,before} of drag.frames){f.x=Math.round(before.x+dx);f.y=Math.round(before.y+dy);}
      if(drag.kind==='nodes')for(const row of drag.rows){const m=G.inverse(row.parentMatrix),a=G.point(m,p),b=G.point(m,drag.p);row.node.x=Math.round(row.before.x+a.x-b.x);row.node.y=Math.round(row.before.y+a.y-b.y);}
      if(drag.kind==='surface-resize'){const box=E.resizeBox(drag.before,drag.edge,dx,dy,e.shiftKey||(!drag.outerOnly&&drag.edge.length===2));E.resizeSurface(drag.f,drag.before,box,drag.outerOnly);}
      if(drag.kind==='resize'){const {row,before,edge}=drag,m=G.inverse(row.matrix),a=G.point(m,p),b=G.point(m,drag.p),box=E.resizeBox(before,edge,a.x-b.x,a.y-b.y,e.shiftKey);Object.assign(row.node,C.copy(before));if(row.node.type==='group')G.resizeGroup(row.node,box.width,box.height);Object.assign(row.node,box);if(row.node.type==='text'){row.node.textResize='fixed';syncText(row.node);}}
      if(drag.kind==='marquee'){drag.box={x:Math.min(p.x,drag.p.x),y:Math.min(p.y,drag.p.y),width:Math.abs(dx),height:Math.abs(dy)};const b=drag.box,inside=r=>r.x>=b.x&&r.y>=b.y&&r.x+r.width<=b.x+b.width&&r.y+r.height<=b.y+b.height,frames=G.surfaces(scene()).filter(f=>f.visible!==false&&!f.locked&&inside(frameRect(f)));scene().surfaceSelection=[...new Set([...(drag.baseFrames||[]),...frames.map(f=>f.id)])];scene().selection=[...new Set([...drag.base,...G.surfaces(scene()).filter(f=>f.visible!==false&&!f.locked&&!scene().surfaceSelection.includes(f.id)).flatMap(f=>f.nodes.filter(n=>{const r=G.bounds(n);return n.visible&&!n.locked&&inside({...r,x:r.x+f.x,y:r.y+f.y});}).map(n=>n.id))])];if(scene().surfaceSelection.length)scene().selection=[];}
      drag.moved=Math.abs(dx||e.clientX-drag.x)>1/view().zoom||Math.abs(dy||e.clientY-drag.y)>1/view().zoom;draw();
    };
    canvas.onpointerup=canvas.onpointercancel=e=>{const d=drag;drag=null;canvas.style.cursor=tool==='text'?'text':'default';if(!d)return;if(d.kind==='text-create'){const p=d.current,box=d.moved?{width:Math.abs(p.x-d.p.x),height:Math.abs(p.y-d.p.y)}:null;createText(box?{x:Math.min(p.x,d.p.x),y:Math.min(p.y,d.p.y)}:d.p,box?.width>5&&box?.height>5?box:null);return;}if(d.moved&&['nodes','resize','frames','surface-resize'].includes(d.kind))change(d.kind==='surface-resize'?(d.outerOnly?'调整画框外框':'缩放画框与内容'):d.kind==='resize'?'调整图层大小':d.kind==='frames'?'移动画框':'移动图层');else{H.save();H.library();renderInspector();draw();}};
    canvas.ondblclick=e=>{const p=world(e),f=surface(),n=G.hit(f.nodes,{x:p.x-f.x,y:p.y-f.y},false);if(n){if(n.type==='instance')editInstance(n,p);else{const child=G.hit(f.nodes,{x:p.x-f.x,y:p.y-f.y},true);select(f,child);if(child.type==='text')inlineText(child);}}};
    canvas.ondragover=e=>{if([...e.dataTransfer.types].some(t=>t==='Files'||t==='application/x-qingjing-content-source'))e.preventDefault();};
    canvas.ondrop=async e=>{e.preventDefault();e.stopPropagation();$('drop-overlay').hidden=true;const position=world(e),target=G.surfaces(scene()).slice().reverse().find(f=>position.x>=f.x&&position.y>=f.y&&position.x<=f.x+f.width&&position.y<=f.y+f.height);if(target)scene().selectedSurface=target.id;if(e.dataTransfer.files.length){const assets=await H.importFiles([...e.dataTransfer.files]);for(const a of assets)if(a.type==='image')addAsset(a,position);}else{const id=e.dataTransfer.getData('application/x-qingjing-content-source'),asset=H.sources().find(a=>a.id===id);if(asset)addAsset(asset,position);}};
    document.addEventListener('keydown',e=>{
      if(!active()||$('dialog').open||P.isFontOpen()||e.target.closest('input,textarea,select,[contenteditable]'))return;const mod=e.metaKey||e.ctrlKey,k=e.key.toLowerCase();let handled=true;
      if(mod&&k==='z')undo(e.shiftKey);else if(mod&&k==='y')undo(true);
      else if(mod&&k==='c')copySelection();else if(mod&&k==='x')copySelection(true);else if(mod&&k==='v')paste();
      else if(mod&&k==='d'){if(scene().selection.length){G.duplicate(scene());change('复制图层');}else copyFrame();}
      else if(mod&&k==='g')e.shiftKey?ungroup():group();else if(mod&&e.altKey&&k==='k')component();
      else if(k==='delete'||k==='backspace')remove();else if(k==='[')reorder(-1);else if(k===']')reorder(1);
      else if(e.code==='Space'){space=true;canvas.style.cursor='grab';}
      else if(k==='+'||k==='=')zoom(1.2);else if(k==='-')zoom(1/1.2);else if(k==='0'||(e.shiftKey&&e.code==='Digit1'))fit();else if(e.shiftKey&&e.code==='Digit2')fit(true);
      else if(k.startsWith('arrow')){const amount=e.shiftKey?10:1,rows=G.roots(scene()).filter(r=>!r.node.locked);for(const r of rows){if(k==='arrowleft')r.node.x-=amount;if(k==='arrowright')r.node.x+=amount;if(k==='arrowup')r.node.y-=amount;if(k==='arrowdown')r.node.y+=amount;}if(rows.length)change('微调图层位置');else{const frames=G.selectedSurfaces(scene()).filter(f=>!f.locked);for(const f of frames){if(k==='arrowleft')f.x-=amount;if(k==='arrowright')f.x+=amount;if(k==='arrowup')f.y-=amount;if(k==='arrowdown')f.y+=amount;}if(frames.length)change('微调画框位置');}}
      else if(k==='f2'){document.querySelector('[data-gallery-param="name"]')?.focus();document.querySelector('[data-gallery-param="name"]')?.select();}
      else if(k==='escape'){scene().selection=[];scene().surfaceSelection=[];setTool('select');H.library();renderInspector();draw();}
      else if(!mod&&k==='f')addFrame();else if(!mod&&k==='t')setTool('text');else if(!mod&&k==='r')add('rect');else if(!mod&&k==='v'){setTool('select');canvas.focus();}else handled=false;
      if(handled){e.preventDefault();e.stopImmediatePropagation();}
    });
    document.addEventListener('keyup',e=>{if(e.code==='Space'){space=false;canvas.style.cursor='default';}});window.addEventListener('blur',()=>{space=false;drag=null;});
  }
  function reset(){P.closeFont();cache.clear();drag=null;space=false;editorInput?.remove();editorInput=null;finishText=null;lastWork=null;tool='select';document.querySelector('[data-gallery-tool="select"]').classList.add('active');$('gallery-add-text').classList.remove('active');canvas.style.cursor='default';}
  window.GalleryEditor={mount,render,draw,fit,addAsset,renderLayers,renderComponents,bindLibrary,reset,refresh:()=>{cache.clear();draw();}};
})();
