/* Local editing cache. Media is immutable and may be shared by independent copies. */
(function(root){
  'use strict';
  const request=r=>new Promise((resolve,reject)=>{r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});
  const done=tx=>new Promise((resolve,reject)=>{tx.oncomplete=()=>resolve();tx.onabort=tx.onerror=()=>reject(tx.error||new Error('本地存储事务未完成'));});
  const tombstone=id=>`deleted:${id}`;
  let opening;
  function open(){return opening ||= new Promise((resolve,reject)=>{const r=indexedDB.open('qingjing-creator-projects',1);r.onupgradeneeded=()=>{r.result.createObjectStore('projects',{keyPath:'id'});r.result.createObjectStore('media',{keyPath:'id'});r.result.createObjectStore('meta');};r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);r.onblocked=()=>reject(new Error('请关闭旧版创作台标签后重试'));});}
  async function list({deleted=false}={}){const db=await open(),tx=db.transaction(['projects','meta']);const [records,keys,values]=await Promise.all([request(tx.objectStore('projects').getAll()),request(tx.objectStore('meta').getAllKeys()),request(tx.objectStore('meta').getAll())]);const markers=new Map(keys.map((key,i)=>[key,values[i]]));return records.map(r=>({...r,deletedAt:markers.get(tombstone(r.id))||r.deletedAt})).filter(r=>!!r.deletedAt===deleted).sort((a,b)=>(deleted?b.deletedAt:b.updatedAt).localeCompare(deleted?a.deletedAt:a.updatedAt));}
  async function load(id,{includeDeleted=false}={}){const db=await open(),tx=db.transaction(['projects','meta']);const [record,marker]=await Promise.all([request(tx.objectStore('projects').get(id)),request(tx.objectStore('meta').get(tombstone(id)))]);if(!record)return undefined;record.deletedAt=marker||record.deletedAt;return record.deletedAt&&!includeDeleted?undefined:record;}
  async function media(ids){const db=await open(),tx=db.transaction('media'),store=tx.objectStore('media');return Promise.all(ids.map(id=>request(store.get(id))));}
  async function last(){const db=await open();return request(db.transaction('meta').objectStore('meta').get('lastProject'));}
  async function write(stores,work){const db=await open(),tx=db.transaction(stores,'readwrite'),finished=done(tx);try{const result=await work(tx);await finished;return result;}catch(error){try{tx.abort();}catch{}await finished.catch(()=>{});throw error;}}
  async function save(project,assets=[],{activate=true}={}){return write(['projects','media','meta'],async tx=>{const projects=tx.objectStore('projects'),meta=tx.objectStore('meta');const [existing,marker]=await Promise.all([request(projects.get(project.id)),request(meta.get(tombstone(project.id)))]);if(marker||existing?.deletedAt)throw new Error('这个项目已移入回收站，不能继续保存');for(const asset of assets)tx.objectStore('media').put(asset);projects.put(project);if(activate)meta.put(project.id,'lastProject');});}
  async function trash(id){return write(['projects','meta'],async tx=>{const projects=tx.objectStore('projects'),meta=tx.objectStore('meta');const [record,lastId]=await Promise.all([request(projects.get(id)),request(meta.get('lastProject'))]);if(!record)throw new Error('项目不存在');record.deletedAt=new Date().toISOString();projects.put(record);meta.put(record.deletedAt,tombstone(id));if(lastId===id)meta.delete('lastProject');});}
  async function restore(id){return write(['projects','meta'],async tx=>{const projects=tx.objectStore('projects'),record=await request(projects.get(id));if(!record)throw new Error('项目不存在');delete record.deletedAt;record.updatedAt=new Date().toISOString();projects.put(record);tx.objectStore('meta').delete(tombstone(id));return record;});}
  async function setThumbnail(id,thumbnail){return write(['projects','meta'],async tx=>{const projects=tx.objectStore('projects');const [record,marker]=await Promise.all([request(projects.get(id)),request(tx.objectStore('meta').get(tombstone(id)))]);if(record&&!marker&&!record.deletedAt&&!record.thumbnail){record.thumbnail=thumbnail;projects.put(record);}});}
  const Local={list,load,media,last,save,trash,restore,setThumbnail}, B=root.CreatorBackend;
  let synchronization, synchronized=false;
  document.addEventListener('creator-connection',()=>{synchronized=false;});
  async function cacheRecord(record){const assets=record.media||[];const data={...record,_creatorPending:false};delete data.media;await write(['projects','media','meta'],async tx=>{tx.objectStore('projects').put(data);for(const asset of assets)tx.objectStore('media').put(asset);const meta=tx.objectStore('meta');if(data.deletedAt)meta.put(data.deletedAt,tombstone(data.id));else meta.delete(tombstone(data.id));});return data;}
  async function synchronize(){if(!B.connected)return;if(synchronized)return;if(synchronization)return synchronization;synchronization=(async()=>{const cached=[...await Local.list(),...await Local.list({deleted:true})];for(const row of cached)row.media=(await Local.media(row.mediaIds||[])).filter(Boolean);const records=await B.migrate('projects',cached);for(const record of records)await cacheRecord(record);synchronized=true;})().finally(()=>synchronization=null);return synchronization;}
  async function serverList(options={}){if(!B.connected)return Local.list(options);await synchronize();const records=await B.list('projects');const cached=[];for(const record of records)cached.push(await cacheRecord(record));return cached.filter(r=>!!r.deletedAt===!!options.deleted).sort((a,b)=>String(b.updatedAt).localeCompare(String(a.updatedAt)));}
  async function serverLoad(id,options={}){if(!B.connected)return Local.load(id,options);await synchronize();const record=await B.get('projects',id);if(!record)return undefined;const cached=await cacheRecord(record);return cached.deletedAt&&!options.includeDeleted?undefined:cached;}
  async function serverSave(record,assets=[],options={}){await Local.save({...record,_creatorPending:true},assets,options);if(!B.connected)return;const rows=(await Local.media(record.mediaIds||[])).filter(Boolean);await B.put('projects',{...record,media:rows});for(const item of record.data?.content?.items||[])await B.put('works',{...item,id:record.id+'_'+item.id,workId:item.id,projectId:record.id,media:rows.filter(a=>item.assetIds.includes(a.id))});await Local.save({...record,_creatorPending:false},[],options);}
  async function serverTrash(id){await B.requireConnection();const record=await serverLoad(id);if(!record)throw new Error('项目不存在');await B.put('projects',{...record,deletedAt:new Date().toISOString(),media:(await Local.media(record.mediaIds||[])).filter(Boolean)});await Local.trash(id);}
  async function serverRestore(id){await B.requireConnection();const record=await serverLoad(id,{includeDeleted:true});if(!record)throw new Error('项目不存在');delete record.deletedAt;record.updatedAt=new Date().toISOString();await B.put('projects',{...record,media:(await Local.media(record.mediaIds||[])).filter(Boolean)});return Local.restore(id);}
  async function serverThumbnail(id,thumbnail){if(!B.connected)return Local.setThumbnail(id,thumbnail);const record=await serverLoad(id);if(!record||record.thumbnail)return;record.thumbnail=thumbnail;await serverSave(record,[],{activate:false});}
  root.ProjectStore={list:serverList,load:serverLoad,media,last,save:serverSave,trash:serverTrash,restore:serverRestore,setThumbnail:serverThumbnail,synchronize,cache:Local};
})(window);
