import com.fasterxml.jackson.databind.ObjectMapper;
import com.qingjing.wallpaper.delivery.packageformat.SecurePackageCodec;
import java.nio.file.*;
import java.security.*;
import java.security.spec.*;
import java.util.*;

/** Local emulator fixture generated by the actual API codec. Never a production publisher. */
public class NativePackageFixture {
    public static void main(String[] args) throws Exception {
        Path root=Path.of(args[0]); Files.createDirectories(root);
        Path privateFile=root.resolve("signing-private.der"); PrivateKey signing; PublicKey publicKey;
        if(Files.exists(privateFile)) {
            var privateKey=(java.security.interfaces.RSAPrivateCrtKey)KeyFactory.getInstance("RSA")
                .generatePrivate(new PKCS8EncodedKeySpec(Files.readAllBytes(privateFile)));
            signing=privateKey; publicKey=KeyFactory.getInstance("RSA").generatePublic(new RSAPublicKeySpec(privateKey.getModulus(),privateKey.getPublicExponent()));
        } else {
            var pair=KeyPairGenerator.getInstance("RSA"); pair.initialize(2048); var generated=pair.generateKeyPair();
            signing=generated.getPrivate(); publicKey=generated.getPublic(); Files.write(privateFile,signing.getEncoded());
            Files.setPosixFilePermissions(privateFile,java.nio.file.attribute.PosixFilePermissions.fromString("rw-------"));
        }
        Files.writeString(root.resolve("build.env"),"export QJ_LOCAL_PACKAGE_SIGNING_KEY_ID=native-fixture-v2\nexport QJ_LOCAL_PACKAGE_PUBLIC_KEY_DER="+Base64.getEncoder().encodeToString(publicKey.getEncoded())+"\n");
        var mapper=new ObjectMapper(); var codec=new SecurePackageCodec(mapper);
        for(String type:List.of("STATIC_IMAGE","VIDEO","LAYER_PARALLAX")) {
            var payloads=new ArrayList<SecurePackageCodec.Payload>();
            if(type.equals("STATIC_IMAGE")) payloads.add(new SecurePackageCodec.Payload("STATIC_IMAGE",0,"image/png",Files.readAllBytes(root.resolve("static.png"))));
            else if(type.equals("VIDEO")) payloads.add(new SecurePackageCodec.Payload("VIDEO",0,"video/mp4",Files.readAllBytes(root.resolve("video.mp4"))));
            else {
                payloads.add(new SecurePackageCodec.Payload("BACKGROUND",0,"image/png",Files.readAllBytes(root.resolve("background.png"))));
                payloads.add(new SecurePackageCodec.Payload("FOREGROUND",0,"image/png",Files.readAllBytes(root.resolve("foreground.png"))));
                payloads.add(new SecurePackageCodec.Payload("PARALLAX_CONFIG",0,"application/json",Files.readAllBytes(root.resolve("parallax.json"))));
            }
            long variant=type.equals("STATIC_IMAGE")?202:type.equals("VIDEO")?203:204;
            var encoded=codec.encode(new SecurePackageCodec.Identity(101,variant,1,type),payloads,"native-fixture-v2",signing);
            Files.write(root.resolve(type+".4dwp"),encoded.encrypted());
            Path key=root.resolve(type+".content-key"); Files.write(key,encoded.contentKey());
            Files.setPosixFilePermissions(key,java.nio.file.attribute.PosixFilePermissions.fromString("rw-------"));
            var version=Map.of("id",Long.toString(variant+100),"variantId",Long.toString(variant),"versionNo",1,"platform","ANDROID","resourceType",type,"manifestSha256",encoded.manifestSha256());
            var metadata=Map.of("formatVersion",2,"sizeBytes",encoded.encrypted().length,"plaintextSizeBytes",encoded.encrypted().length-36,
                "encryptedSha256",encoded.encryptedSha256(),"plaintextSha256",encoded.plaintextSha256(),"signingKeyId","native-fixture-v2","keyAlgorithm","RSA-OAEP-SHA256-MGF1-SHA1");
            Files.write(root.resolve(type+".json"),mapper.writeValueAsBytes(Map.of("deliveryMode","SECURE_PACKAGE","wallpaperId","101","downloadUrl","/api/v1/delivery/files","resourceVersion",version,"package",metadata)));
            Arrays.fill(encoded.contentKey(),(byte)0);
        }
    }
}
